Casio/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Casio.Models;
using IdentitySample.Models;
using Microsoft.AspNet.Identity;

namespace Casio.Controllers
{
    public class CourseController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Course
        public ActionResult Index()
        {
            if (User.IsInRole("Admin"))
            {
                var courses = db.Courses.Include(c => c.Teacher);
                return View(courses.ToList());
            }

            if (User.IsInRole("Teacher"))
            {
                string userId = User.Identity.GetUserId();
                var courses = db.Courses.Include(c => c.Teacher)
                    .Where(p => p.TeacherId == userId);
                return View(courses.ToList());
            }

            if (User.IsInRole("Student"))
            {
                string userId = User.Identity.GetUserId();
                var enrollments = db.Enrollments.Where(p => p.StudentId == userId && p.Grade > 0).ToList();

                List<Course> courses = new List<Course>();
                foreach (Enrollment enrollment in enrollments)
                {
                    Course course = db.Courses.FirstOrDefault(c => c.Id == enrollment.CourseId);
                    if (course != null)
                    {
                        courses.Add(course);
                    }
                }

                return View(courses);
            }

            return RedirectToAction("Index", "Home");
        }

        // GET: Course/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }

            if (User.IsInRole("Teacher"))
            {
                course.Enrollments = db.Enrollments.Where(p => p.CourseId == id).ToList();
            }

            if (User.IsInRole("Student"))
            {
                string userId = User.Identity.GetUserId();
                course.Enrollments = db.Enrollments.Where(p => p.CourseId == id && p.StudentId == userId).ToList();
            }
            return View(course);
        }

        // GET: Course/Create
        public ActionResult Create()
        {
            if (User.IsInRole("Teacher"))
            {
                string userId = User.Identity.GetUserId();
                ViewBag.TeacherId = new SelectList(db.Teachers.Where(p => p.Id == userId), "Id", "Name");
            } else
            {
                ViewBag.TeacherId = new SelectList(db.Teachers, "Id", "Name");
            }
            return View();
        }

        // POST: Course/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Code,Name,Credit,Description,TeacherId")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TeacherId = new SelectList(db.Teachers, "Id", "Name", course.TeacherId);
            return View(course);
        }

        // GET: Course/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            ViewBag.TeacherId = new SelectList(db.Teachers, "Id", "Name", course.TeacherId);
            return View(course);
        }

        // POST: Course/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Code,Name,Credit,Description,TeacherId")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TeacherId = new SelectList(db.Teachers, "Id", "Name", course.TeacherId);
            return View(course);
        }

        // GET: Course/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Course/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Course course = db.Courses.Find(id);
            db.Courses.Remove(course);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Casio/Controllers/EnrollmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Casio.Models;
using IdentitySample.Models;
using Microsoft.AspNet.Identity;

namespace Casio.Controllers
{
    public class EnrollmentController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Enrollment
        public ActionResult Index()
        {
            var enrollments = db.Enrollments.Include(e => e.Course).Include(e => e.Student);
            string userId = User.Identity.GetUserId();
            if (User.IsInRole("Teacher"))
            {
                enrollments = enrollments.Where(p => p.Course.TeacherId == userId);
            }
            if (User.IsInRole("Student"))
            {
                enrollments = enrollments.Where(p => p.StudentId == userId);
            }
            return View(enrollments.ToList());
        }

        // GET: Enrollment/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            return View(enrollment);
        }

        // GET: Enrollment/Create
        public ActionResult Create()
        {
            if (User.IsInRole("Teacher"))
            {
                string userId = User.Identity.GetUserId();
                ViewBag.CourseId = new SelectList(db.Courses.Where(p => p.TeacherId == userId), "Id", "FullName");
            } else
            {
                ViewBag.CourseId = new SelectList(db.Courses, "Id", "FullName");
            }
            if (User.IsInRole("Student"))
            {
                string userId = User.Identity.GetUserId();
                ViewBag.StudentId = new SelectList(db.Students.Where(p => p.Id == userId), "Id", "FullName");
            }
            else
            {
                ViewBag.StudentId = new SelectList(db.Students, "Id", "FullName");
            }
            return View();
        }

        // POST: Enrollment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,StudentId,CourseId,Grade")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                enrollment.DateModified = DateTime.Now; //set date
                db.Enrollments.Add(enrollment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            if (User.IsInRole("Teacher"))
            {
                string userId = User.Identity.GetUserId();
                ViewBag.CourseId = new SelectList(db.Courses.Where(p => p.TeacherId == userId), "Id", "FullName");
            }
            else
            {
                ViewBag.CourseId = new SelectList(db.Courses, "Id", "FullName");
            }
            if (User.IsInRole("Student"))
            {
                string userId = User.Identity.GetUserId();
                ViewBag.StudentId = new SelectList(db.Students.Where(p => p.Id == userId), "Id", "FullName");
            }
            else
            {
                ViewBag.StudentId = new SelectList(db.Students, "Id", "FullName");
            }
            return View(enrollment);
        }

        // GET: Enrollment/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            if (User.IsInRole("Teacher"))
            {
                string userId = User.Identity.GetUserId();
                ViewBag.CourseId = new SelectList(db.Courses.Where(p => p.TeacherId == userId), "Id", "FullName");
            }
            else
            {
                ViewBag.CourseId = new SelectList(db.Courses, "Id", "FullName");
            }
            if (User.IsInRole("Student"))
            {
                string userId = User.Identity.GetUserId();
                ViewBag.StudentId = new SelectList(db.Students.Where(p => p.Id == userId), "Id", "FullName");
            }
            else
            {
                ViewBag.StudentId = new SelectList(db.Students, "Id", "FullName");
            }
            return View(enrollment);
        }

        // POST: Enrollment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,StudentId,CourseId,Grade")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                enrollment.DateModified = DateTime.Now; //change date
                db.Entry(enrollment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            if (User.IsInRole("Teacher"))
            {
                string userId = User.Identity.GetUserId();
                ViewBag.CourseId = new SelectList(db.Courses.Where(p => p.TeacherId == userId), "Id", "FullName");
            }
            else
            {
                ViewBag.CourseId = new SelectList(db.Courses, "Id", "FullName");
            }
            if (User.IsInRole("Student"))
            {
                string userId = User.Identity.GetUserId();
                ViewBag.StudentId = new SelectList(db.Students.Where(p => p.Id == userId), "Id", "FullName");
            }
            else
            {
                ViewBag.StudentId = new SelectList(db.Students, "Id", "FullName");
            }
            return View(enrollment);
        }

        // GET: Enrollment/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            return View(enrollment);
        }

        // POST: Enrollment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Enrollment enrollment = db.Enrollments.Find(id);
            db.Enrollments.Remove(enrollment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Casio/Views/Course/Create.cshtml
@model Casio.Models.Course

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Credit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Credit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Credit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeacherId, "Teacher", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TeacherId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TeacherId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Casio/Views/Course/Delete.cshtml
@model Casio.Models.Course

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.Teacher.Name)*@
            Teacher
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Teacher.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Credit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Credit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Casio/Views/Course/Details.cshtml
@model Casio.Models.Course

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.Teacher.Name)*@
            Teacher
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Teacher.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Credit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Credit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        @if (User.IsInRole("Student"))
        {
            foreach (var item in Model.Enrollments)
            {
                <dt>
                    @Html.DisplayNameFor(model => item.Grade)
                </dt>
                <dd>
                    @Html.DisplayFor(model => item.Grade)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => item.DateModified)
                </dt>
                <dd>
                    @Html.DisplayFor(model => item.DateModified)
                </dd>
            }
        }
    </dl>
</div>

@if (User.IsInRole("Teacher"))
{
    <h4>List of students in this course</h4>
    if (Model.Enrollments == null)
    {
        <hr />
        <p>No students found in this course.</p>
    }

    <table class="table">
        <tr>
            <th>
                Username
            </th>
            <th>
                Student
            </th>
            <th>
                Grade
            </th>
            <th>
            </th>
        </tr>

        @foreach (var item in Model.Enrollments)
        {
            <tr>
                <td>
                    @item.Student.UserName
                </td>
                <td>
                    @item.Student.Name
                </td>
                <td>
                    @item.Grade
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Enrollment", new { id = item.Id }, null) |
                    @Html.ActionLink("Details", "Details", "Enrollment", new { id = item.Id }, null) |
                    @Html.ActionLink("Delete", "Delete", "Enrollment", new { id = item.Id }, null)
                </td>
            </tr>
        }
    </table>
}

<p>
    @if (!User.IsInRole("Student"))
    {
        <span>@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |</span>
    }
    @Html.ActionLink("Back to List", "Index")
</p>

Casio/Views/Course/Edit.cshtml
@model Casio.Models.Course

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Credit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Credit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Credit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeacherId, "Teacher", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TeacherId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TeacherId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Casio/Views/Course/Index.cshtml
@model IEnumerable<Casio.Models.Course>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @if (!User.IsInRole("Student"))
    {
        <span>@Html.ActionLink("Create New", "Create")</span>
    }
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Teacher.Name)*@
            Teacher
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Credit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Teacher.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Credit)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @if (!User.IsInRole("Student"))
            {
                <span>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }) |
                </span>
            }
            @Html.ActionLink("Details", "Details", new { id = item.Id })
        </td>
    </tr>
}

</table>